In [1]:
import pandas as pd

### READ DATA

In [4]:
pd.read_csv("netflix1.csv")

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

### SET DATA

In [60]:
data = pd.read_csv("netflix1.csv")

In [ ]:
data.head()

In [7]:
data.tail()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

### CHECK FOR NaN VALUES

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

### START TASKS

In [ ]:
''' TASKS
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations
'''

## DELETE REDUNDANT COLUMNS

data.head()

In [61]:
# DROP RATINGS FOR CLEANING
data.drop(columns = "rating", inplace = True)

In [49]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [ ]:
''' TASKS
Deleting redundant columns.            X  
Renaming the columns.                  
Dropping duplicates.                   
Cleaning individual columns.           
Remove the NaN values from the dataset 
Check for some more Transformations    
'''

## RENAMING COLUMNS

In [50]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [62]:
# COLUMN NAMES START WITH CAP
new_column_names = []

for i in data.columns:
    new_column_names.append(i.capitalize())

In [63]:
new_column_names

['Show_id',
 'Type',
 'Title',
 'Director',
 'Country',
 'Date_added',
 'Release_year',
 'Duration',
 'Listed_in']

In [64]:
data.columns = new_column_names

In [65]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [ ]:
''' TASKS
Deleting redundant columns.            X  
Renaming the columns.                  X
Dropping duplicates.                   
Cleaning individual columns.           
Remove the NaN values from the dataset 
Check for some more Transformations    
'''

## DROP DUPLICATES

In [21]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8785    False
8786    False
8787    False
8788    False
8789    False
Length: 8790, dtype: bool

In [23]:
data.duplicated().sum()

np.int64(0)

In [42]:
# IF YOU HAD DUPLIACES , we do not in this case
data.drop_duplicates(inplace = True)

In [ ]:
''' TASKS
Deleting redundant columns.            X  
Renaming the columns.                  X
Dropping duplicates.                   X
Cleaning individual columns.           
Remove the NaN values from the dataset 
Check for some more Transformations    
'''

## CLEAN INDIVIDUAL COLUMNS

In [ ]:
# Shows booleans cell-wise
data.isna()

In [26]:
# Shows column-wise
data.isna().sum()

Show_id         0
Type            0
Title           0
Director        0
Country         0
Date_added      0
Release_year    0
Duration        0
Listed_in       0
dtype: int64

In [27]:
# IF WE HAD NaN VALUES
data.dropna(inplace = True)

In [ ]:
''' TASKS
Deleting redundant columns.            X  
Renaming the columns.                  X
Dropping duplicates.                   X
Cleaning individual columns.           X
Remove the NaN values from the dataset X
Check for some more Transformations    
'''

## CHECK FOR MORE TRANSFORMATIONS

In [28]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [66]:
# Show_id column we only want integers
# check if all rows has s with show_id
data["Show_id"].unique()

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'],
      shape=(8790,), dtype=object)

In [67]:
# lambda to remove s from id
data["Show_id"].apply(lambda x: x.split("s")[1])

0          1
1          3
2          6
3         14
4          8
        ...
8785    8797
8786    8798
8787    8801
8788    8784
8789    8786
Name: Show_id, Length: 8790, dtype: object

In [68]:
# SETTING THE CHANGES
data["Show_id"] = data["Show_id"].apply(lambda x: x.split("s")[1])

In [ ]:
data

In [70]:
# CHANGE DATA TYPE
type(data["Show_id"][0])

str

In [72]:
# CHANGE STR TO INT
data["Show_id"].astype(int)

0          1
1          3
2          6
3         14
4          8
        ...
8785    8797
8786    8798
8787    8801
8788    8784
8789    8786
Name: Show_id, Length: 8790, dtype: int64

In [74]:
# SET THE CHANGES
data["Show_id"] = data["Show_id"].astype(int)

In [75]:
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,1 Season,Kids' TV

In [77]:
# YEAR COLUMN FROM / TO -
data["Date_added"].apply(lambda x: x.replace("/","-"))

0        9-25-2021
1        9-24-2021
2        9-24-2021
3        9-22-2021
4        9-24-2021
           ...
8785     1-17-2017
8786     9-13-2018
8787    12-15-2016
8788     6-23-2018
8789      6-7-2018
Name: Date_added, Length: 8790, dtype: object

In [79]:
# SET THE CHANGES
data["Date_added"] = data["Date_added"].apply(lambda x: x.replace("/","-"))

In [80]:
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9-25-2021,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9-24-2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9-24-2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9-22-2021,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9-24-2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1-17-2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9-13-2018,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12-15-2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6-23-2018,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6-7-2018,2016,1 Season,Kids' TV

In [81]:
# CAN ALSO GRAB SPECIFIC DATA
df = data["Country"].value_counts().reset_index()
df[df["Country"] == "Turkey"]

   Country  count
13  Turkey    112

In [ ]:
''' TASKS
Deleting redundant columns.            X  
Renaming the columns.                  X
Dropping duplicates.                   X
Cleaning individual columns.           X
Remove the NaN values from the dataset X
Check for some more Transformations    X
'''

## EXPORT DATA

In [84]:
data.to_csv("Cleaned_Data_CSV.csv", index=False)

In [85]:
data.to_excel("Cleaned_data_Excel.xlsx", index = False)