In [3]:
import pandas as pd

In [ ]:
data = pd.read_csv("Airbnb_Open_Data.csv")

In [6]:
data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [7]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

### CHECK FOR NaN

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [ ]:
''' TASKS
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations
'''

# 1. Deleting redundant columns

In [ ]:
data.columns

In [10]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'id']

In [11]:
len(columns_to_keep)

19

In [12]:
len(columns_to_drop)

7

## 1st Method, Filtering Data

In [17]:
df = data[columns_to_keep]

In [ ]:
#data.shape
df

## 2nd Method, Dropping Columns

In [ ]:
data.columns

In [ ]:
# DROP A SINGLE COLUMN
#data.drop(columns = ["license"])

In [22]:
# Drop columns using filter
data.drop(columns = columns_to_drop, inplace=True)

data

In [ ]:
''' TASKS
Deleting redundant columns.                 X
Renaming the columns.                            
Dropping duplicates.                      
Cleaning individual columns.                
Remove the NaN values from the dataset      
Check for some more Transformations         
'''

# 2. Renaming the columns

In [25]:
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [29]:
# Change the column NAME to Name
data.rename(columns= {"NAME": "Name"}, inplace=True)

In [31]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [ ]:
# WE HAVE NO MORE COLUMNS TO RENAME
# a solution if u wanted all upper-case
new_columns_names = []
for i in data.columns:
    new_columns_names.append(i.upper())

In [ ]:
# make a copy just in case
new_dataframe_to_modify = data.copy()

In [ ]:
new_dataframe_to_modify.columns = new_columns_names

In [ ]:
new_dataframe_to_modify

In [ ]:
''' TASKS
Deleting redundant columns.                 X
Renaming the columns.                       X     
Dropping duplicates.                        
Cleaning individual columns.                
Remove the NaN values from the dataset      
Check for some more Transformations         
'''

# 3. Dropping Duplicates

In [34]:
# Show series duplicates in cells as booleans
data.duplicated()
# Shows total amount of duplicates
data.duplicated().sum()
# Shows both total # true and false
data.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [36]:
# Drop and Set changes with inplace or store in var
data.drop_duplicates(inplace=True)

In [37]:
# Check for 0 duplicates
data.duplicated().sum()

np.int64(0)

In [ ]:
''' TASKS
Deleting redundant columns.                 X
Renaming the columns.                       X     
Dropping duplicates.                        X
Remove the NaN values from the dataset
Cleaning individual columns.                     
Check for some more Transformations         
'''

# 4. Remove NaN Values

In [39]:
# Show NaN cell-wise
data.isna()
# Get the amount column-wise
data.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [ ]:
# Drop a single column
data.drop(columns=["last review"], inplace=True)

In [41]:
# Drop all NaN Values
data.dropna(inplace = True)

In [42]:
data.isna().sum()

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
last review               0
dtype: int64

In [ ]:
''' TASKS
Deleting redundant columns.                 X
Renaming the columns.                       X     
Dropping duplicates.                        X
Remove the NaN values from the dataset      X
Cleaning individual columns.                     
Check for some more Transformations         
'''

# 5. Cleaning Individual Columns

In [44]:
# CHANGE THE SERIES IN THIS COLUMN TO ALL UPPERCASE
data["host_identity_verified"].str.upper()

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 83969, dtype: object

In [46]:
# SET THE CHANGES
data["host_identity_verified"] = data["host_identity_verified"].str.upper()

In [47]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0,4/25/2019
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0,6/27/2018
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0,6/10/2019
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0,6/23/2019
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0,6/29/2019

In [48]:
# CHANGE TRUE AND FALSE TO BOOLEANS FOR TRAINING MODELS
data["instant_bookable"].apply(lambda x: 1 if x == True else 0)

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: instant_bookable, Length: 83969, dtype: int64

In [54]:
# SET THE CHANGES 
data["instant_bookable"] = data["instant_bookable"].apply(lambda x: 1 if x == True else 0)

In [ ]:
data.head()

In [55]:
# RESET INDEX FOR PROPER ORDERING
data.reset_index(inplace=True)

In [56]:
# CHECK TYPE OF COLUMNS SERIES WE CHANGED
type(data["instant_bookable"][15])

numpy.int64

In [ ]:
''' TASKS
Deleting redundant columns.                 X
Renaming the columns.                       X     
Dropping duplicates.                        X
Remove the NaN values from the dataset      X
Cleaning individual columns.                X     
Check for some more Transformations         
'''

# 6. Check for more Transformations

In [57]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0,4/25/2019
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0,6/27/2018
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0,6/10/2019
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0,6/23/2019
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0,6/29/2019

In [58]:
# FIX THE TYPES FOR COLUMNS
type(data["price"][15])

str

In [59]:
data["price"].head(3)

0    $966
1    $142
2    $204
Name: price, dtype: object

In [60]:
# Replace $ with empty string
data["price"].str.replace("$", "")

0          966
1          142
2          204
3          577
4        1,060
          ...
83964      822
83965      455
83966    1,078
83967      103
83968      982
Name: price, Length: 83969, dtype: object

In [61]:
# Set the changes
data["price"] = data["price"].str.replace("$", "")

In [62]:
data["price"]

0          966
1          142
2          204
3          577
4        1,060
          ...
83964      822
83965      455
83966    1,078
83967      103
83968      982
Name: price, Length: 83969, dtype: object

In [63]:
# REMOVE COMMAS IN THE 1000s place
data["price"].str.replace(",","")

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: object

In [65]:
# Set the changes
data["price"] = data["price"].str.replace(",","")

In [66]:
data["price"][15]

'370 '

In [67]:
# FIX SPACE AT END OF PRICE
data["price"] = data["price"].str.replace(" ","")

In [70]:
data["price"][15]

'370'

In [71]:
# CHANGE DATA TYPE 
type(data["price"][1])

str

In [72]:
# Changes column to int datatype
data["price"].astype(int)

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: int64

In [73]:
# Check the type
#type(data["price"].astype(int)[1])

numpy.int64

In [74]:
# SET THE CHANGES 
data["price"] = data["price"].astype(int)

In [75]:
# Check the type for set changes
type(data["price"][1])

numpy.int64

# EXPORTING DATA

## CSV

In [76]:
# Export to csv
data.to_csv("Cleaned_Data.csv")

In [ ]:
# Read the csv file
pd.read_csv("Cleaned_Data.csv")

## Excel

In [80]:
# Export to excel with index
data.to_excel("Excel_cleaned_data.xlsx", index=False)

In [81]:
# Read the xlsx file
pd.read_excel("Excel_cleaned_data.xlsx")

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,$193,10,9,10/19/2021
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,$28,30,45,5/21/2022
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,$41,10,9,11/19/2018
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013,577,$115,3,74,6/22/2019
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,$212,45,49,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,822,$164,1,9,4/25/2019
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015,455,$91,4,36,6/27/2018
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020,1078,$216,1,58,6/10/2019
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,103,$21,7,40,6/23/2019
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022,982,$196,1,239,6/29/2019