In [1]:
import pandas as pd

# 1a.LOAD CSV DATA

In [6]:
data = pd.read_csv("HR-Employee-Attrition.csv")

In [7]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

# 1b.CHECK FOR NaN VALUES

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

# 1c.START TRANSFORMING TASKS

In [ ]:
''' TASKS
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations
'''

## 1.DELETE REDUNDANT COLUMNS

In [14]:
# create filters for columns kept and dropped
columns_to_keep = ['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager' ]
columns_to_drop = ['EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance']

In [9]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
# CHECK THE DATA TABLE
data.head(3).iloc[:,13:22]

In [15]:
# WE KEEP 13
len(columns_to_keep)

13

In [19]:
# WE DROP 22
len(columns_to_drop)

22

In [18]:
# 35 TOTAL COLUMNS
data.shape

(1470, 35)

## 1st method

In [22]:
# FILTERING THE DATA WITH OUR COLUMNS
#data[['Age', 'Attrition', 'BusinessTravel']] or: data[columns_to_keep]
new_data = data[columns_to_keep]

## 2nd method

In [29]:
# INPLACE sets the new dataframe or you can reassign to a variable
#data.drop(columns = ["Age", "Attrition"], inplace = True) or:
#data_new = data.drop(columns = ["Age", "Attrition"]
#data_new_2 = data.drop(columns = columns_to_drop)   CHECKS FOR CHANGED TABLE
data.drop(columns = columns_to_drop,inplace= True)   # sets dataframe

In [30]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [ ]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    
Dropping duplicates.                     
Cleaning individual columns.             
Remove the NaN values from the dataset   
Check for some more Transformations      
'''

## 2.RENAMING THE COLUMNS

In [31]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [33]:
# CHANGE COLUMN NAME MANUALLY
data.rename(columns = {"DistanceFromHome": "DistanceHome"},inplace = True)

In [36]:
data.rename(columns = {"DailyRate": "DailyWage", 'HourlyRate': 'HourlyWage'})

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [ ]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    x
Dropping duplicates.                     
Cleaning individual columns.             
Remove the NaN values from the dataset   
Check for some more Transformations      
'''

## 3.DROPPING DUPLICATES

In [39]:
# CHECK FOR ANY DUPLICATES
#data.duplicated()
#data.duplicated().head(20
data.duplicated().sum()

np.int64(0)

In [ ]:
# WE HAVE NO DUPLICATES BUT IF WE DID DO
data.drop_duplicates(inplace=True)

In [ ]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    x
Dropping duplicates.                     x
Cleaning individual columns.             
Remove the NaN values from the dataset   
Check for some more Transformations      
'''

## 4.CLEAN INDIVIDUAL COLUMNS

In [44]:
data.shape
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [41]:
# EXAMPLE METHODS
# FILTER FOR ANYONE WITH <= YearsAtCompany
data[data["YearsAtCompany"] <= 8].shape

(1022, 13)

In [43]:
# FILTER FOR YES IN ATTRITION COLUMN
data[data["Attrition"] == "Yes"]["Attrition"].unique()

array(['Yes'], dtype=object)

In [74]:
### MAKE A COPY SO WE HAVE MODIFIED DATA N OG DATA
modify_data = data.copy()

In [75]:
modify_data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [76]:
# REPLACE UNDERSCORES

# check type first
type(modify_data["BusinessTravel"][1])

# now we clean column
modify_data["BusinessTravel"].str.replace("_", " ")

0           Travel Rarely
1       Travel Frequently
2           Travel Rarely
3       Travel Frequently
4           Travel Rarely
              ...
1465    Travel Frequently
1466        Travel Rarely
1467        Travel Rarely
1468    Travel Frequently
1469        Travel Rarely
Name: BusinessTravel, Length: 1470, dtype: object

In [77]:
# SET CHANGES TO MODIFY_DATA
modify_data["BusinessTravel"] = modify_data["BusinessTravel"].str.replace("_"," ")

In [78]:
modify_data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [ ]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    x
Dropping duplicates.                     x
Cleaning individual columns.             x
Remove the NaN values from the dataset   
Check for some more Transformations      
'''

## 5.REMOVE NaN VALUES

In [58]:
# CHECK FOR NAN VALUES
modify_data.isna()        # booleans

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,False,False,False,False,False,False,False,False,False,False,False,False,False
1466,False,False,False,False,False,False,False,False,False,False,False,False,False
1467,False,False,False,False,False,False,False,False,False,False,False,False,False
1468,False,False,False,False,False,False,False,False,False,False,False,False,False
1469,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
# CHECK FOR NAN VALUES
modify_data.isna().sum()              # NAN count column wise
#modify_data.isna().sum().tail(3)     # works too

Age                        0
Attrition                  0
BusinessTravel             0
DailyRate                  0
Department                 0
DistanceHome               0
Education                  0
HourlyRate                 0
JobRole                    0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [60]:
# WE HAVE NO NAN VALUES BUT DO THIS IF SO
data.dropna(inplace = True)
data = data.dropna()

In [61]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    x
Dropping duplicates.                     x
Cleaning individual columns.             x
Remove the NaN values from the dataset   x
Check for some more Transformations      
'''

## 6.CHECK FOR MORE TRANSFORMATIONS

In [62]:
modify_data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [ ]:
# CHANGE ATTITION TO '1 Yes' or '2 No' with lambda
#modify_data["Attrition"].apply(lambda x: 1 if x == "Yes" else 0)

In [79]:
# APPLIES THE CHANGES
modify_data["Attrition"] = modify_data["Attrition"].apply(lambda x: 1 if x == "Yes" else 0)

In [80]:
modify_data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,0,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,0,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,0,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,0,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [82]:
# CHECK WE CHANGED THE TYPE
type(modify_data["Attrition"][1])

numpy.int64

In [ ]:
''' TASKS
Deleting redundant columns.              x
Renaming the columns.                    x
Dropping duplicates.                     x
Cleaning individual columns.             x
Remove the NaN values from the dataset   x
Check for some more Transformations      x
'''

## EXPORTING DATA

In [ ]:
modify_data

### CSV

In [84]:
# INDEX SETS A # COLUMN INDEX ON THE LEFT OF ROWS
modify_data.to_csv("Cleaned_Data.csv",index = False)

In [85]:
# READS THE NEWLY CLEANED FILE
pd.read_csv("Cleaned_Data.csv").head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2

### Excel

In [89]:
# EXPORT TO EXCEL WITH INDEX TRUE
modify_data.to_excel("Cleaned_Excel.xlsx", index = True)

In [90]:
# READ EXCEL OUTPUT
pd.read_excel("Cleaned_Excel.xlsx").head()

,Unnamed: 0,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2