In [1]:
import pandas as pd

WHEN TO USE IT

- You have more than 3 cleaning steps
- You want readable preprocessing
- You build ML or analytics pipelines
- You hate scrolling up and down notebooks

In [ ]:
WHEN NOT TO USE IT

- One-liner transformations
- Simple exploratory analysis
- Tiny throwaway scripts

### .pipe makes our data cleaning code readable,clean,reusable

In [ ]:
.pipe()

In [4]:
# EXAMPLE DICT DATASET
data = {
    "Name": ["Alice", "BOB", "Charlie", None],
    "Age": ["25", "30", "?", "40"],
    "Salary": ["50000", "60000", "not available", "70000"]
}

In [20]:
# PASS OUR DICT AS DATAFRAME
df = pd.DataFrame(data)

In [ ]:
df

In [7]:
# GET RID OFF UPPERCASE IN Name Column
df["Name"] = df["Name"].str.strip().str.title()

In [ ]:
df

In [9]:
# GET RID OF None in Name
df = df[df["Name"].notna()]

In [10]:
df

      Name Age         Salary
0    Alice  25          50000
1      Bob  30          60000
2  Charlie   ?  not available

In [ ]:
# CHANGE AGE ? to NaN 
df["Age"] = pd.to_numeric(df["Age"], errors = "coerce")

In [15]:
# DROP NaN
df = df.dropna(subset= ["Age"])
df["Salary"] = pd.to_numeric(df["Salary"], errors= "coerce")

In [14]:
df

    Name   Age Salary
0  Alice  25.0  50000
1    Bob  30.0  60000

### - code above not scalable/ hard to debug. NOW WE USE PIPE

## pipe lets you pass dataframes thru custom functions

In [16]:
def clean_names(df):
    df = df.copy()
    df["Name"] = df["Name"].str.strip().str.title()
    return df[df["Name"].notna()]

def clean_age(df):
    df = df.copy()
    df["Age"] = pd.to_numeric(df["Age"], errors = "coerce")
    return df.dropna(subset = ["Age"])

def clean_salary(df):
    df = df.copy()
    df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
    return df

In [17]:
clean_df = (
    df
    .pipe(clean_names)
    .pipe(clean_age)
    .pipe(clean_salary)
)

In [18]:
clean_df

    Name   Age  Salary
0  Alice  25.0   50000
1    Bob  30.0   60000

In [21]:
df

      Name Age         Salary
0    Alice  25          50000
1      BOB  30          60000
2  Charlie   ?  not available
3     None  40          70000

In [23]:
# APPLYING TO UNCLEANED DATAFRAME
df.pipe(clean_names).pipe(clean_age).pipe(clean_salary)

    Name   Age  Salary
0  Alice  25.0   50000
1    Bob  30.0   60000

In [24]:
# Create another function for min age
def filter_min_age(df, min_age):
    return df[df["Age"] >= min_age]

In [25]:
df.pipe(clean_names).pipe(clean_age).pipe(clean_salary).pipe(filter_min_age, min_age = 27)

  Name   Age  Salary
1  Bob  30.0   60000